const APP_URL = process.env.VUE_APP_REDSTONE_APP_BASE_URL;
const API_BASE_URL = process.env.VUE_APP_REDSTONE_API_BASE_URL;
const API_VERSION = process.env.VUE_APP_REDSTONE_API_VERSION;
const STOREFRONT_API_BASE_URL = process.env.VUE_APP_STOREFRONT_API_BASE_URL;

const LOCAL_DOMAIN = "http://localhost:8065";
const IS_LOCAL_HOST = window.location.hostname === "localhost" ? true : false;

export interface IConstants {
  REDSTONE_AUTH_USER: string;
  REDSTONE_AUTH_TOKEN: string;
  REDSTONE_AUTH_BUSINESS: string;
  REDSTONE_AUTH_BUSINESS_TOKEN: string;
  REDSTONE_APP_URL: string;
  REDSTONE_API_URL: string;
  REDSTONE_API_VERSION: string;
  STOREFRONT_API_URL: string;
}

const constants: IConstants = {
  REDSTONE_AUTH_USER: "REDSTONE_AUTH_USER",
  REDSTONE_AUTH_TOKEN: "REDSTONE_AUTH_TOKEN",
  REDSTONE_AUTH_BUSINESS: "REDSTONE_AUTH_BUSINESS",
  REDSTONE_AUTH_BUSINESS_TOKEN: "REDSTONE_AUTH_BUSINESS_TOKEN",
  REDSTONE_APP_URL: IS_LOCAL_HOST ? LOCAL_DOMAIN : APP_URL,
  REDSTONE_API_URL: API_BASE_URL,
  REDSTONE_API_VERSION: API_VERSION,
  STOREFRONT_API_URL: STOREFRONT_API_BASE_URL,
};

export default constants;
