export const imported_invoices = [
  {
    ach_payment_initiated: false,
    invoice_id: "7157827000000093402",
    zcrm_potential_id: "",
    customer_id: "7157827000000093368",
    zcrm_potential_name: "",
    customer_name: "Vesicash",
    company_name: "Vesicash",
    status: "draft",
    invoice_number: "INV-000003",
    reference_number: "",
    date: "2025-10-06",
    due_date: "2025-10-06",
    due_days: "",
    email: "",
    project_name: "",
    billing_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    shipping_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    country: "",
    phone: "",
    created_by: "Elvis Efemena",
    total: 60000,
    balance: 60000,
    payment_expected_date: "",
    custom_fields: [],
    custom_field_hash: {},
    salesperson_name: "",
    shipping_charge: 0,
    adjustment: 0,
    created_time: "2025-10-06T22:17:27+0100",
    last_modified_time: "2025-10-06T22:17:27+0100",
    updated_time: "2025-10-06T22:17:27+0100",
    is_viewed_by_client: false,
    has_attachment: false,
    client_viewed_time: "",
    is_emailed: false,
    color_code: "",
    current_sub_status_id: "",
    current_sub_status: "draft",
    currency_id: "7157827000000093159",
    schedule_time: "",
    currency_code: "NGN",
    currency_symbol: "NGN",
    template_type: "standard",
    no_of_copies: 1,
    show_no_of_copies: true,
    transaction_type: "renewal",
    reminders_sent: 0,
    last_reminder_sent_date: "",
    last_payment_date: "",
    template_id: "7157827000000017001",
    documents: "",
    salesperson_id: "",
    write_off_amount: 0,
    exchange_rate: 1,
    unprocessed_payment_amount: 0,
  },
  {
    ach_payment_initiated: false,
    invoice_id: "7157827000000093356",
    zcrm_potential_id: "",
    customer_id: "7157827000000093322",
    zcrm_potential_name: "",
    customer_name: "James Micheal",
    company_name: "BlackRock",
    status: "draft",
    invoice_number: "INV-000002",
    reference_number: "",
    date: "2025-10-07",
    due_date: "2025-10-07",
    due_days: "",
    email: "james@vesicash.com",
    project_name: "",
    billing_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    shipping_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    country: "",
    phone: "",
    created_by: "Elvis Efemena",
    total: 3000,
    balance: 3000,
    payment_expected_date: "",
    custom_fields: [],
    custom_field_hash: {},
    salesperson_name: "",
    shipping_charge: 0,
    adjustment: 0,
    created_time: "2025-10-06T20:38:15+0100",
    last_modified_time: "2025-10-06T20:38:15+0100",
    updated_time: "2025-10-06T20:38:15+0100",
    is_viewed_by_client: false,
    has_attachment: false,
    client_viewed_time: "",
    is_emailed: false,
    color_code: "",
    current_sub_status_id: "",
    current_sub_status: "draft",
    currency_id: "7157827000000093159",
    schedule_time: "",
    currency_code: "NGN",
    currency_symbol: "NGN",
    template_type: "standard",
    no_of_copies: 1,
    show_no_of_copies: true,
    transaction_type: "renewal",
    reminders_sent: 0,
    last_reminder_sent_date: "",
    last_payment_date: "",
    template_id: "7157827000000017001",
    documents: "",
    salesperson_id: "",
    write_off_amount: 0,
    exchange_rate: 1,
    unprocessed_payment_amount: 0,
  },
  {
    ach_payment_initiated: false,
    invoice_id: "7157827000000093306",
    zcrm_potential_id: "",
    customer_id: "7157827000000093272",
    zcrm_potential_name: "",
    customer_name: "Efemena",
    company_name: "Vesicash",
    status: "draft",
    invoice_number: "INV-000001",
    reference_number: "",
    date: "2025-10-06",
    due_date: "2025-10-06",
    due_days: "",
    email: "elvis+1@vesicash.com",
    project_name: "",
    billing_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    shipping_address: {
      address: "",
      street2: "",
      city: "",
      state: "",
      zipcode: "",
      country: "",
      phone: "",
      fax: "",
      attention: "",
    },
    country: "",
    phone: "",
    created_by: "Elvis Efemena",
    total: 50,
    balance: 50,
    payment_expected_date: "",
    custom_fields: [],
    custom_field_hash: {},
    salesperson_name: "",
    shipping_charge: 0,
    adjustment: 0,
    created_time: "2025-10-06T12:57:27+0100",
    last_modified_time: "2025-10-06T12:57:27+0100",
    updated_time: "2025-10-06T12:57:27+0100",
    is_viewed_by_client: false,
    has_attachment: false,
    client_viewed_time: "",
    is_emailed: false,
    color_code: "",
    current_sub_status_id: "",
    current_sub_status: "draft",
    currency_id: "7157827000000093159",
    schedule_time: "",
    currency_code: "NGN",
    currency_symbol: "NGN",
    template_type: "standard",
    no_of_copies: 1,
    show_no_of_copies: true,
    transaction_type: "renewal",
    reminders_sent: 0,
    last_reminder_sent_date: "",
    last_payment_date: "",
    template_id: "7157827000000017001",
    documents: "",
    salesperson_id: "",
    write_off_amount: 0,
    exchange_rate: 1,
    unprocessed_payment_amount: 0,
  },
];

export const transformed_invoice = {
  business_id: "BIZ12658941251",
  irn: "INV000001-807EFF90-20251006",
  issue_date: "2025-10-06",
  due_date: "2025-10-06",
  issue_time: "11:57:27",
  invoice_type_code: "396",
  payment_status: "PENDING",
  note: "Thanks for your business.",
  tax_point_date: "2025-10-06",
  document_currency_code: "NGN",
  tax_currency_code: "NGN",
  buyer_reference: "7157827000000093272",
  accounting_supplier_party: {
    party_name: "Your Business Name",
    tin: "123456789",
    email: "supplier@example.com",
    telephone: "+2348000000000",
    postal_address: {
      street_name: "",
      city_name: "",
      postal_zone: "",
      country: "NG",
    },
  },
  accounting_customer_party: {
    party_name: "Efemena",
    tin: "TIN-CUSTOMER-PLACEHOLDER",
    email: "customer@example.com",
    telephone: "+2348000000001",
    postal_address: {
      street_name: "",
      city_name: "",
      postal_zone: "",
      country: "NG",
    },
  },
  payment_terms_note: "Due on Receipt",
  tax_total: [
    {
      tax_amount: 0,
      tax_subtotal: [
        {
          taxable_amount: 50,
          tax_amount: 0,
          tax_category: {
            id: "TAX",
            percent: 0,
          },
        },
      ],
    },
  ],
  legal_monetary_total: {
    line_extension_amount: 50,
    tax_exclusive_amount: 50,
    tax_inclusive_amount: 50,
    payable_amount: 50,
  },
  invoice_line: [
    {
      hsn_code: "",
      product_category: "",
      discount_rate: 0,
      discount_amount: 0,
      fee_rate: 0,
      fee_amount: 0,
      invoiced_quantity: 1,
      line_extension_amount: 50,
      item: {
        name: "",
        description: "A pack of matches",
        sellers_item_identification: "",
      },
      price: {
        price_amount: 50,
        base_quantity: 1,
        price_unit: "NGN per 1",
      },
    },
  ],
};
